services:
  expenseserver-db:
    image: postgres
    container_name: expenseserver-db
    ports:
      - "5432:5432" #left side is the host, right side is the container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:

    #first time running
    #docker-compose up --build -d

    #other time
    #docker-compose up -d
